#!/usr/bin/env bash
# We are to Configure nginix so  so that its HTTP response contains a custom header (on web-01 and web-02)

sudo apt update
sudo apt install nginx

header_name = X-Served-By
server_name = $144060-web-01

echo "add_header ${header_name} ${server_name};" | sudo tee -a /etc/nginx/nginx.conf > /dev/null

sudo nginx -t

sudo systemctl reload nginx
