#!/bin/bash

# Install HAproxy
apt-get update
apt-get install -y haproxy

# Configure HAproxy
cat <<EOF > /etc/haproxy/haproxy.cfg
defaults
    mode http
    timeout connect 5000ms
    timeout client 50000ms
    timeout server 50000ms

frontend http-in
    bind *:80
    default_backend servers

backend servers
    mode http
    balance roundrobin
    server web-01 [STUDENT_ID]-web-01:80 check
    server web-02 [STUDENT_ID]-web-02:80 check
EOF

# Set up init script for HAproxy
cat <<EOF > /etc/init.d/haproxy
#!/bin/sh
### BEGIN INIT INFO
# Provides:          haproxy
# Required-Start:    \$local_fs \$network \$syslog
# Required-Stop:     \$local_fs \$network \$syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: HAproxy init script
# Description:       HAproxy init script
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/sbin/haproxy
CONFIG=/etc/haproxy/haproxy.cfg
PIDFILE=/var/run/haproxy.pid

test -x \$DAEMON || exit 0

. /lib/lsb/init-functions

start() {
    \$DAEMON -f \$CONFIG -D -p \$PIDFILE
    sleep 2
    status
}

stop() {
    \$DAEMON -f \$CONFIG -D -p \$PIDFILE -sf \$(cat \$PIDFILE)
    rm -f \$PIDFILE
}

status() {
    status_of_proc -p \$PIDFILE \$DAEMON haproxy && exit 0 || exit \$?
}

case "\$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    reload|force-reload|restart)
        stop
        start
        ;;
    status)
        status
        ;;
    *)
        echo "Usage: /etc/init.d/haproxy {start|stop|reload|restart|status}"
        exit 1
        ;;
esac

exit 0
EOF

chmod +x /etc/init.d/haproxy
update-rc.d haproxy defaults

# Start HAproxy
service haproxy start
