#!/usr/bin/env bash
# A script that contains the solutions to what is keeping your Ubuntu container Nginx installation from listening on port 80.
mv /etc/nginx/sites-enabled/default /etc/nginx/sites-enabled/default.bak
ln -s /etc/nginx/sites-available/config /etc/nginx/sites-enabled/
ngnix -t
sudo restart ngnix
