#!/bin/bash

# Check if an argument was provided
if [ $# -ne 1 ]; then
  echo "Usage: $0 <username>"
  exit 1
fi

# Switch to the user passed as an argument and print the current user
su -c 'whoami' $1
